# This entity is just for testing components and systems during development.
# It will be removed from the final game.
name: Guard Dog
components:
  - !Guard
  - !Vision
  - !Hearing
  - !Stunnable
  - !LinearSpeed 0.5
  - !AngularSpeed 270
  - !Physics { radius: 0.375 }
  - !Footsteps { sound_wave: Guard }
  - !Scene models/animated/Fox.glb#Scene0
  - !DefaultAnimation Idle
  - !Animations
    Idle: models/animated/Fox.glb#Animation0
    Run: models/animated/Fox.glb#Animation2
    Puzzled: models/animated/Fox.glb#Animation0
    Shocked: models/animated/Fox.glb#Animation1

