name: Tough Guard
components:
  - !Guard
  - !Eyes
  - !Ears
  - !Mover
  - !Physics { radius: 0.375 }
  - !Footsteps { sound_wave: Guard }
  # - !Scene models/animated/Fox.glb#Scene0
  # - !AnimationClips
  #   Idle: models/animated/Fox.glb#Animation2
  #   Run: models/animated/Fox.glb#Animation0
  #   Puzzled: models/animated/Fox.glb#Animation2
  #   Shocked: models/animated/Fox.glb#Animation1

# Slightly shorter vision cone than Advanced Guard.
