name: Briefcase Pickup
components:
  - !Pickup
  # - !Mesh3D
  #   scene: <fill in later!>
  - !DropShadow

# Triggers temporary wall blocking exit to open.
# Triggers unique "Acquired" message along the top.
# Triggers story dialog along the bottom.
