name: Briefcase Pickup
components:
  - !Pickup
  - !DropShadow
  # - !Mesh3D
  #   scene: <fill in later!>

# Triggers temporary wall blocking exit to open.
# Triggers unique "Acquired" message along the top.
# Triggers story dialog along the bottom.
