name: Door Wall
components:
  - !Door
  - !Barrier
  - !BlocksVision
  - !DeflectsSounds
# - !Scene models/animated/Fox.glb#Scene0

#   States:
#     Opening
#     Opened
#     Closing
#     Closed
#
# Stops blocking vision and deflecting sound only when it's FULLY open!
