name: Door Wall
components:
  - !Wall
  - !BlocksVision
  - !DeflectsSounds
# - !Mesh3D

#   States:
#     Opening
#     Opened
#     Closing
#     Closed
#
# Stops blocking vision and deflecting sound only when it's FULLY open!
