name: Glass Wall
components:
  - !Door
  - !Wall
  - !DeflectsSounds
  - !Shatterable
# - !Mesh3D

# Shatter isn't triggered by the sound waves, it's triggered by being
# in the gun's area of effect and it sending out an event to the affected
# glass walls!
