# A translucent wall that can be shattered by being in the Shockwave Cannon's
# area of effect when it's fired. Doesn't block vision.
name: Glass Wall
components:
  - !Door
  - !Wall
  - !DeflectsSounds
  - !Shatterable
# - !Scene models/animated/Fox.glb#Scene0
