name: Temporary Wall
components:
  - !Wall
# - !Mesh3D
  - !BlocksVision
  - !DeflectsSounds

#   States:
#     Lowering
#     Raising
#     Idle
#
# Stops blocking vision and deflecting sound only when it's FULLY open!
