name: Temporary Wall
components:
# - !Mesh3D
  - !BlocksVision
  - !DeflectsSounds

#   States:
#     Lowering
#     Raising
#     Idle
#
# Needs to stop blocking vision and deflecting sound when it opens.
