name: Floor Switch
components:
  - !FloorSwitch
# - !Trigger
  # - !Scene models/animated/Fox.glb#Scene0
  # - !AnimationClips
  #   Idle: models/animated/Fox.glb#Animation2
  #   Run: models/animated/Fox.glb#Animation0
  #   Puzzled: models/animated/Fox.glb#Animation2
  #   Shocked: models/animated/Fox.glb#Animation1

# Opens all associated doors temporarily!
