name: Guard
components:
  - !Guard
  - !Vision
  - !Hearing
  - !Stunnable
  - !Mover
  - !Physics { radius: 0.375 }
  - !Footsteps { sound_wave: Guard }
  # - !Animation3D
  #   scene: <fill in later!>
